---
title: "Lab03 - ME315"
author: "Tiago Pierre Fernandes"
format: pdf
editor: visual
---

# Questão 1

```{r}
library(readxl)
library(tidyverse)
```

# Questão 2

```{r}
fname <- "WDIEXCEL.xlsx"
file.exists(fname)
```

# Questão 3

```{r}
countries <- read_excel(fname, sheet = "Country")
countries
```

# Questão 4

```{r}
countries <- countries %>%
  filter(`Short Name` %in% c("Brazil", "Monaco", "Morocco", "Germany", "Qatar"))
countries
```

# Questão 5

```{r}
WDI <- read_excel(fname, sheet = "Data")
```

# Questão 6

```{r}
WDI <- WDI %>%
select("Country Code","Indicator Code", "1960":"2018")
```

# Questão 7

```{r}
WDI <- WDI %>% 
  pivot_longer(
    cols = "1960":"2018",
    names_to = "YEAR",
    values_to = "Valor" 
  )
WDI
```

# Questão 8

```{r}
WDI <- WDI|>
  mutate(YEAR = as.integer(YEAR))
```

# Questão 9

```{r}
WDI_final <- WDI %>%
  semi_join(countries, by = "Country Code") %>%
  filter(`Indicator Code` == "SP.DYN.CBRT.IN") %>%
  left_join(countries %>%
      select(`Country Code`, `Short Name`), by = "Country Code") %>%
  pivot_wider(names_from = `Indicator Code`, values_from = Valor) %>%
  select(`Country Code`, `Short Name`, YEAR, `SP.DYN.CBRT.IN`)

WDI_final
```

# Questão 10

```{r}
WDI_final <- WDI_final %>%
  arrange(`Short Name`, YEAR)

WDI_final
```

# Questão 11

```{r}
ggplot(WDI_final, aes(x = YEAR, y = `SP.DYN.CBRT.IN`, color = `Short Name`)) +
  geom_line(linewidth = 1) +
  labs(title = "Índice SP.DYN.CBRT.IN por país", 
       x = "Ano", 
       y = "SP.DYN.CBRT.IN",
       color = "País") +
  theme_minimal()
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```














